(import (chezscheme)
	(srfi :0)
	(srfi :64)
	(srfi :204))
(define non-linear-pattern #t)
(define non-linear-pred #t)
(define non-linear-field #t)
(define record-implemented #t)
(define test-name "srfi-test")
(define scheme-version-name (scheme-version))
(include "r6rs-srfi-common.scm")
(exit)
;;; $~/.akku/env
